#!/bin/bash

DESTDIR=/var/www/www.ouba.org/htdocs/opensource/portage
SVNPATH=/var/svn/repos
MODULE=/trunk/ouba-overlay

cd /tmp
rm -rf ouba-overlay
svn export -r HEAD file://"${SVNPATH}${MODULE}" ouba-overlay
cd ouba-overlay
make
cd portage-final
rm -rf "${DESTDIR}"/*
mv * "${DESTDIR}"
cd /tmp
rm -rf ouba-overlay
chown -R root:root "${DESTDIR}"
find "${DESTDIR}" -type d -exec chmod 755 {} \;
find "${DESTDIR}" -type f -exec chmod 644 {} \;